# -*- coding: utf-8 -*-
"""simylator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSqYWMuk0EE46GsWSk1Y45uQ_BAogWJk
"""

import random
import math

# ======================
# Классы симуляторов (из вашего файла)
# ======================

class Node:
    def __init__(self, node_id):
        self.id = node_id
        self.knows_failure = False

class BaseSimulator:
    def __init__(self, num_nodes, interval, node_failures_pct):
        self.nodes = [Node(i) for i in range(num_nodes)]
        self.interval = interval
        self.node_failures_pct = node_failures_pct
        self.failed_nodes = set()
        self.bandwidth_usage = 0

    def simulate_failure(self):
        num_failures = int(len(self.nodes) * self.node_failures_pct / 100)
        if num_failures > 0:
            self.failed_nodes = set(random.sample(range(len(self.nodes)), num_failures))
        # Один живой узел знает о сбое
        alive = [n for n in self.nodes if n.id not in self.failed_nodes]
        if alive:
            alive[0].knows_failure = True

    def detect_failures(self):
        pass

    def run_simulation(self):
        self.simulate_failure()
        current_time = 0
        max_time = 30  # сек

        while current_time <= max_time:
            self.detect_failures()
            alive_nodes = [n for n in self.nodes if n.id not in self.failed_nodes]
            knowing = [n for n in alive_nodes if n.knows_failure]
            if len(knowing) == len(alive_nodes):
                return current_time, self.bandwidth_usage
            current_time += self.interval
        return max_time, self.bandwidth_usage

class SerfSimulator(BaseSimulator):
    def __init__(self, num_nodes, gossip_interval, gossip_fanout, packet_loss_pct, node_failures_pct):
        super().__init__(num_nodes, gossip_interval, node_failures_pct)
        self.gossip_fanout = gossip_fanout
        self.packet_loss_pct = packet_loss_pct

    def detect_failures(self):
        for node in self.nodes:
            if node.id not in self.failed_nodes and node.knows_failure:
                candidates = [i for i in range(len(self.nodes)) if i != node.id and i not in self.failed_nodes]
                if not candidates:
                    continue
                targets = random.sample(candidates, min(self.gossip_fanout, len(candidates)))
                for t in targets:
                    if random.random() > self.packet_loss_pct / 100.0:
                        self.nodes[t].knows_failure = True
                    self.bandwidth_usage += 1

class HeartbeatSimulator(BaseSimulator):
    def detect_failures(self):
        for node in self.nodes:
            if node.id not in self.failed_nodes:
                for other in self.nodes:
                    if other.id != node.id:
                        if other.id in self.failed_nodes:
                            node.knows_failure = True
                        self.bandwidth_usage += 1

# ======================
# Эксперименты
# ======================

def run_experiment_once(sim_class, **kwargs):
    """Запускает симуляцию один раз и возвращает время конвергенции"""
    sim = sim_class(**kwargs)
    time, _ = sim.run_simulation()
    return time

def average_over_runs(sim_class, runs=5, **kwargs):
    """Усредняет результат по нескольким запускам"""
    times = [run_experiment_once(sim_class, **kwargs) for _ in range(runs)]
    return round(sum(times) / len(times), 1)

# ----------------------
# Эксперимент 1: Влияние Gossip Interval
# ----------------------
print("Эксперимент 1: Влияние Gossip Interval (50 узлов, 5% потерь, 10% отказов)")
print("-" * 70)
print(f"{'Interval (сек)':<15} | {'Время конвергенции (сек)':<25}")
print("-" * 70)

intervals = [0.1, 0.2, 0.5, 1.0]
for iv in intervals:
    avg_time = average_over_runs(
        SerfSimulator,
        num_nodes=50,
        gossip_interval=iv,
        gossip_fanout=3,
        packet_loss_pct=5,
        node_failures_pct=10
    )
    print(f"{iv:<15} | {avg_time:<25}")

# ----------------------
# Эксперимент 2: Влияние количества узлов
# ----------------------
print("\nЭксперимент 2: Влияние количества узлов (Gossip Interval=0.2, Fanout=3)")
print("-" * 70)
print(f"{'Nodes':<10} | {'Время конвергенции (сек)':<25} | {'Теория: 0.2·log₃(N)':<20}")
print("-" * 70)

node_counts = [10, 25, 50, 100]
for n in node_counts:
    avg_time = average_over_runs(
        SerfSimulator,
        num_nodes=n,
        gossip_interval=0.2,
        gossip_fanout=3,
        packet_loss_pct=5,
        node_failures_pct=10
    )
    theory = round(0.2 * math.log(n) / math.log(3), 2)
    print(f"{n:<10} | {avg_time:<25} | {theory:<20}")

# ----------------------
# Эксперимент 3: Влияние потери пакетов
# ----------------------
print("\nЭксперимент 3: Влияние потери пакетов (50 узлов, Gossip Interval=0.2)")
print("-" * 60)
print(f"{'Packet Loss (%)':<18} | {'Время конвергенции (сек)':<25}")
print("-" * 60)

losses = [0, 5, 20]
for loss in losses:
    avg_time = average_over_runs(
        SerfSimulator,
        num_nodes=50,
        gossip_interval=0.2,
        gossip_fanout=3,
        packet_loss_pct=loss,
        node_failures_pct=10
    )
    print(f"{loss:<18} | {avg_time:<25}")

# ----------------------
# Сравнение Gossip vs Heartbeat (для 50 узлов)
# ----------------------
print("\nСравнение Gossip vs Heartbeat (50 узлов, 10% отказов)")
print("-" * 60)
print(f"{'Протокол':<15} | {'Время конвергенции (сек)':<25}")
print("-" * 60)

gossip_time = average_over_runs(
    SerfSimulator,
    num_nodes=50,
    gossip_interval=0.2,
    gossip_fanout=3,
    packet_loss_pct=5,
    node_failures_pct=10
)

heartbeat_time = average_over_runs(
    HeartbeatSimulator,
    num_nodes=50,
    interval=0.2,
    node_failures_pct=10
)

print(f"{'Gossip':<15} | {gossip_time:<25}")
print(f"{'Heartbeat':<15} | {heartbeat_time:<25}")